### ISSUE TITLE
Add Auth class to abstract model classes.

### ISSUE THREAD

**Issue by tristan-fickes-bfg** [bigfishgames/GameBenchAPI-PyClient#17]
**Is your feature request related to a problem? Please describe.**
As an engineer, I don't want the client to be required to import two modules in order to make requests through the GameBench API Client.  Currently, both the 'authentication.py' and 'modelcreator.py' modules have to be imported to retrieve authentication tokens and session metrics.

**Describe the solution you'd like**
I want a solution that will allow the client to communicate with a single module to send requests.  This can be done by following Aaron's suggestion of adding a class member reference to the AbstractModel.  Once a model is called it will contact the Authenticator to retrieve the auth token.

**Comment by aaron-wilson-bfg** [comment]
Hi Tristan! Great idea to reduce the burden on clients. I'd like to suggest that all abstract data frame models have a class member referencing the Auth singleton. They will all just point to the same object.
