### ISSUE TITLE
Refactor the models to add the required information to the request parameters

### ISSUE THREAD

**Issue by tristan-fickes-bfg** [bigfishgames/GameBenchAPI-PyClient#28]
As a software engineer, I want the models to be responsible for creating a dictionary of required key/value pairs to pass through the system so that the user doesn't have to worry about knowing the exact information to pass in with each request to the library.

The models should create a dictionary and add the key/value pairs that are needed by the library to send the proper request.  

Currently, the abstract models are adding an 'auth_token' key to the passed in dictionary.  This should be updated to create the dictionary and add that key/value.  The individual models should then add the keys that are required for that specific request.  The abstract models should also take in the Session ID as that will have to be passed in from the user.

Done Means:
- Models are responsible for adding the needed key/value pairs to the request_parameters dictionary.

**Comment by aaron-wilson-bfg** [comment]
Good Morning @tristan-fickes-bfg and @kawika-brennan-bfg 
The member variable in the models' `__init__` will definitely work. I'd like you to consider this alternative:

```python
import abc

class AbstractTimeSeriesModel(abc.ABC):
    METRIC_PATH = ''

    def __init__(self):
        super().__init__()
        self.request_parameters = dict() # just here for the scratch demo to work.
        self.request_parameters["metric"] = self.METRIC_PATH




class Battery(AbstractTimeSeriesModel):
    """ Object to set the Battery information for a session."""
    METRIC_PATH = "/battery"

    def __init__(self):
        super().__init__()


class SomethingElse(AbstractTimeSeriesModel):
    """ Object to set the Battery information for a session."""

    def __init__(self):
        super().__init__()


x = Battery()
print(x.request_parameters)
y = SomethingElse()
print(y.request_parameters)

Outputs:
{'metric': '/battery'}
{'metric': ''}
```

So the default implementation sets it to an empty string and the class constant is used to set the request parameter in more abstract way.

**Comment by tristan-fickes-bfg** [comment]
This has been implemented in the latest push for the Generic and Time Series models.  It wasn't implemented for the SessionDetail models as these models are being removed in issue #30
