### ISSUE TITLE
Refactor the Session Summary object to have pointers to the different detail elements

### ISSUE THREAD

**Issue by tristan-fickes-bfg** [bigfishgames/GameBenchAPI-PyClient#30]
As a software engineer, I want the SessionSummary object to have pointers to the different details of the DataFrame so that we don't need all of the SessionDetail models.

We will know this is complete when the Session Detail models are removed and the information can be retrieved from the Session Summary object.

**Comment by tristan-fickes-bfg** [comment]
@aaron-wilson-bfg - Just to verify our thought process matches what you were thinking.  We are considering creating getters on the SessionSummary object that will return the detail that the user is wanting.

**Comment by aaron-wilson-bfg** [comment]
@tristan-fickes-bfg 
What are your thoughts on something like:
```python
class SessionSummary(GenericModel):
    self.app_information = get_data().the_access_syntax_to_the_dataframe_element
```
