### ISSUE TITLE
Security Update: URLlib is out of date

### ISSUE THREAD

**Issue by aaron-wilson-bfg** [bigfishgames/GameBenchAPI-PyClient#33]
Please update the dependency urllib dependency.

urllib3 = ">=1.24.2"

**Comment by kawika-brennan-bfg** [comment]
Hey @aaron-wilson-bfg, I added the dependency to setup.py and wanted to make sure it works real quick when I run the 'python setup.py install' command. I am encountering a problem "warning: install_lib: 'build/lib' does not exist -- no Python modules to install". My search online tells me I should run this while in the project directory, which I am. Any ideas on what is going on?

**Comment by aaron-wilson-bfg** [comment]
@kawika-brennan-bfg 
Hmmm. Not sure what's going on. You might also need to update the Pipfile with pipenv.

@tristan-fickes-bfg might have some information here.

**Comment by kawika-brennan-bfg** [comment]
urllib3 was upgraded to 1.25 about 3 hours ago and the dependency is causing an issue:
`urllib3 1.25 is installed but urllib3<1.25,>=1.21.1 is required by {'requests'}`
I have the dependency set as ==1.24.2 for now until I figure out how to support the new version.

**Comment by kawika-brennan-bfg** [comment]
We had to change the urllib3 requirements because the requests library needs urllib3 to be <1.25. The requirements are below

**urllib3==1.24.2**
- requests==2.21.0 [requires: urllib3>=1.21.1,<1.25]
    - requests-mock==1.5.2 [requires: requests>=1.1]
      - gamebench-api-client-big-fish==0.0.1 [requires: requests-mock>=1.5.2]
    - Sphinx==2.0.1 [requires: requests>=2.5.0]
      - recommonmark==0.5.0 [requires: sphinx>=1.3.1]
