### ISSUE TITLE
Modules are not found after 'pip install' of the GameBench API package

### ISSUE THREAD

**Issue by kawika-brennan-bfg** [bigfishgames/GameBenchAPI-PyClient#37]
**Describe the bug**
When installed, inspecting site-packages shows that only a 'dist-info' folder exists. This is different from other packages where they have a package with modules along with a 'dist-info' folder.

**To Reproduce**
1. Activate a python 3.7 virtual environment on your machine
2. Install the package: pip install GameBenchAPI-PyClient-BigFish
3. Observe the python site-packages (I used PyCharm to view)
4. See the GameBenchAPI-PyClient-BigFish folder

**Expected behavior**
A folder containing GameBench API modules exists in addition to the 'dist-info' folder in site-packages.

**Desktop (please complete the following information):**
 - macOS 10.14.4
 - Python 3.7

**Additional context**
Occurs in pull request https://github.com/bigfishgames/GameBenchAPI-PyClient/pull/36
Occurs with package versions 0.1.0 and 0.1.1

**Comment by aaron-wilson-bfg** [comment]
Thanks for writing this up, @kawika-brennan-bfg 
Can you check if this is the case for both versions published to PyPi? https://pypi.org/project/GameBenchAPI-PyClient-BigFish/

**Comment by kawika-brennan-bfg** [comment]
> Thanks for writing this up, @kawika-brennan-bfg
> Can you check if this is the case for both versions published to PyPi? https://pypi.org/project/GameBenchAPI-PyClient-BigFish/

Yeah, no problem! So I just finished checking 0.1.0 and the results are the same as 0.1.1 - no modules.

**Comment by aaron-wilson-bfg** [comment]
@kawika-brennan-bfg 
I've uploaded 0.1.2 to PyPi, can you try now? I think it should be fixed.

**Comment by kawika-brennan-bfg** [comment]
Awesome, it is fixed in 0.1.2! Closing this issue.

**Comment by aaron-wilson-bfg** [comment]
Thanks @kawika-brennan-bfg
