### ISSUE TITLE
The URL class in url_builder.py is outdated and not using the global variable for base URL

### ISSUE THREAD

**Issue by kawika-brennan-bfg** [bigfishgames/GameBenchAPI-PyClient#39]
**Describe the bug**
A blocking issue has been found where the URL class is not using the global base URL. The current hardcoded URL is incorrect and causes an SSL error.

**To Reproduce**
1. Create a new Python 3.7.2 project
2. Install the GameBench API package
3. Import the GAMEBENCH_CONFIG and Authenticator
4. Set the username and password
5. Call the Authenticator
6. Observe the SSL error:

- > requests.exceptions.SSLError: HTTPSConnectionPool(host='api.production.gamebench.net', port=443): Max retries exceeded with url: /v1/Auth/login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate

**Expected behavior**
The GameBench API is able to authenticate, without errors, given the correct username and password.

**Desktop**
 - macOS 10.14.4
 - Python 3.7.2

**Comment by tristan-fickes-bfg** [comment]
This will also need a test to verify the URL Builder is always properly set.
