### ISSUE TITLE
A KeyError occurs when setting the 'auth_token' in AbstractGenericModel

### ISSUE THREAD

**Issue by kawika-brennan-bfg** [bigfishgames/GameBenchAPI-PyClient#42]
**Describe the bug**
When integrating the GameBench API Client, it was found that a KeyError occurs on authenticator.data['token'] when request_parameters['auth_token'] is being set.

**To Reproduce**
1. Create a new Python 3.7.2 project
2. Install the GameBench API package
3. Import the GAMEBENCH_CONFIG and ModelCreator
4. Set the username and password
5. Call the ModelCreator on a TimeSeries model (I used SessionSummary) 
6. Observe the KeyError:

- ` File "/Users/...python3.7/site-packages/gamebench_api_client/models/dataframes/generic/abstract_generic.py", line 26, in __init__
    self.request_parameters['auth_token'] = self.authenticator.data['token']
KeyError: 'token'`

**Expected behavior**
A KeyError does not occur; the auth_token is set without issues. If there is an error message that would help diagnose the problem, that is returned by the api, it would be ideal to see that instead of just the KeyError.

**Desktop:**
- macOS 10.14.4
- Python 3.7.2

**Comment by aaron-wilson-bfg** [comment]
@kawika-brennan-bfg 
Thanks for the report!

Let's make sure we get a regression test in first and also figure out where the gap in the current tests are letting this through.

**Comment by tristan-fickes-bfg** [comment]
With Kawika's help we found the issue and here is what needs to be fixed:
- Update the returned dictionary in  'Attributes.get_headers' method to have the "Content-Type" key be "Content - Type".  The spaces around the hyphen are important.
- Update the "RequestDirect._auth_to_dict" dictionary.  The "auth" key should be deleted and replaced with: 
`'data': {
     'username': auth_object.request.data['username'],
     'password': auth_object.request.data['password']
}`
