### ISSUE TITLE
Dependency 'requests' is not installed when installing the GameBenchAPI-PyClient package

### ISSUE THREAD

**Issue by kawika-brennan-bfg** [bigfishgames/GameBenchAPI-PyClient#43]
**Describe the bug**
When creating a brand new project, it was found that the requests library was needed for the GameBenchAPI-PyClient package after trying to run tests on creating the Authenticator.

**To Reproduce**
- Create a new Python 3.7.2 project
- Install the GameBench API package
- Import the GAMEBENCH_CONFIG and Authenticator
- Set the username and password
- Call the Authenticator
- Observe that an error occurs, detailing that the 'requests' library was not found

**Expected behavior**
All library dependencies are installed when the package is installed.

**Desktop:**
- macOS 10.14.4
- Python 3.7.2

**Comment by aaron-wilson-bfg** [comment]
Whoops! This one is on me. I'll take it and get a fix in quick.

**Comment by aaron-wilson-bfg** [comment]
On hold while I fix a dependency.

This is nearly finished, just need to write a single script to fire off all the scripts needed and drop in the Travis config for it to fire on master only.
