### ISSUE TITLE
GenericModel 'Keyword' is returning a fatal error when given expected data parameters

### ISSUE THREAD

**Issue by kawika-brennan-bfg** [bigfishgames/GameBenchAPI-PyClient#56]
**Describe the bug**
When requesting a model to be created from Keyword, the request's data contains a fatal error. This is occurring when giving the request a data parameter containing a dictionary value.

**To Reproduce**
1. Open a Python 3.7 shell
2. Import GAMEBENCH_CONFIG and ModelCreator
3. Set username, password, and company_id GAMEBENCH_CONFIG variables
4. Instantiate the ModelCreator
5. Use the ModelCreator to request a Keyword with the parameter of an empty session id and data with a dict value, representing what to search for:
- `session_request = {"session_id": "", "data": {"query": "<insert word here>"}}`
6. Observe a fatal error occurs

**Expected behavior**
A request to the GameBench API can be made to query for certain words.

**Desktop (please complete the following information):**
 - macOS 10.14.4
 - Python 3.7.2

**Additional Comments**
This does not occur when using a cURL call https://docs.gamebench.net/api/documentation

**Comment by kawika-brennan-bfg** [comment]
Note: the value in query should not have array brackets []

**Comment by tristan-fickes-bfg** [comment]
The fix for this is merged into Master.
