### ISSUE TITLE
A Fatal Error occurs when adding a "data" dictionary to Session Summary model creation

### ISSUE THREAD

**Issue by kawika-brennan-bfg** [bigfishgames/GameBenchAPI-PyClient#59]
**Describe the bug**
A Fatal Error is occuring when "data" is given as part of the request parameters when creating a model. This is specifically seen when using Session Summary to filter out a list of some defined amount of sessions by a keyword; I am using 'apps' in this scenario.

**To Reproduce**
1. Open a Python 3.7 shell
2. Import GAMEBENCH_CONFIG and ModelCreator
3. Set username, password, and company_id GAMEBENCH_CONFIG variables
4. Instantiate the ModelCreator
5. Use the ModelCreator to request a Session Summary, for the last 15 sessions of a specific App, with the parameter of an empty session id and data with a dict value, representing what to search for:
```
"session_id": "",
"params": "pageSize=15&sort=timePushed%3Adesc",
"data": {"apps": ["<some app name>"]}
```
6. Observe the fatal error

**Expected behavior**
The lastest 15 Session Summaries for the app matching that given name is returned.

**Desktop (please complete the following information):**
 - macOS 10.4.4
 - Python 3.7.2

**Additional context**
This does not occur when attempting this with a cURL command. Note: The cURL command sometimes returns the last 15 sessions regardless of the name, doesn't work with Company ID (param), and sometimes won't retrieve anything. A fatal error does not occur in these instances with cURL.
See the cURL commands for the GameBench API https://docs.gamebench.net/api/documentation

**Comment by tristan-fickes-bfg** [comment]
The fix for this issue was related to the fix for https://github.com/bigfishgames/gamebenchapi-pyclient/issues/56.  That is now merged into Master and this issue resolved.
