### ISSUE TITLE
[Documentation] Update documentation with examples of including data or params in the request

### ISSUE THREAD

**Issue by tristan-fickes-bfg** [bigfishgames/GameBenchAPI-PyClient#61]
As a user of the GameBench Reporting API Client, I want examples of the different types of requests that can be made so that I will be able to use the library properly.  We will know this is complete when the documentation has examples of filtering data by the following:

- Keyword
- Apps
- Device
- Manufacturer

**Comment by kawika-brennan-bfg** [comment]
We should make sure we have both ways of settings the params represented in the documentation:
1) `"params": 'pageSize=15'`
2) `"params": {'pageSize': 5}`
